### ISSUE TITLE
GPL 라이센스 문제

### ISSUE THREAD

**Issue by BasixKOR** [trustypeople/linky#1]
이 소스가 조리퐁님의 소스 기반이라면 조리퐁님은 GPLv3로 배포중이실텐데.. MIT에서 GPL로 바꿔야 하지 않나요?

**Comment by trustypeople** [comment]
흠.. 아직까지는 조리퐁님의 소스는 들어가지 아니합니다. 그리고 대부분의 소스는 제가 제작한 소스가 들어갈 예정이고요. 다만 그렇기에 조리퐁님의 소스가 들어가는 부분부터는 라이센스 충돌이 일어나겠지요?

우선 저는 아예 채팅 시스템부터 제작하는 방식으로 진행하려 합니다. 그렇기에 아직까지는 라이센스의 충돌은 일어나지 않았습니다만. 위에서 언급한대로 조리퐁님의 소스가 나중에는 들어가게 되므로 그 시점부터 라이센스가 바뀔 것으로 보입니다.

**Comment by BasixKOR** [comment]
라이센스가 바뀌면 각각 기여자들에게 허락을 맡아야 하는 불편함이 있을 것으로 보입니다만... 차라리 그것 보다야 현재 라이센스를 바꾸는 편이 어떠신지요? 의견 여전히 같으신 걸로 보이면 이슈 닫겟습니다 :-)

**Comment by trustypeople** [comment]
흠.. 확실히 그렇겠군요.. 아직 기여자는 저 뿐이지만요..

내일 업로드때 아마 라이센스도 바뀌어 있을겁니다.
